dev_directory : /mnt/Directory/dev_data
eval_directory : /mnt/Directory/eval_data
model_directory: 
  baseline: ./model
  idcae: ./model_idcae
result_directory:
  baseline: ./result
  idcae: ./result_idcae
result_file: result.csv

max_fpr : 0.1

feature:
  baseline:
    n_mels: 128
    frames : 5
    n_fft: 1024
    hop_length: 512
    power: 2.0
  idcae:
    n_mels: 128
    frames: 5
    n_fft: 1024
    hop_length: 512
    power: 2.0


fit:
  baseline:
    epochs : 100
    batch_size : 512
    validation_split : 0.1
  idcae:
    epochs: 20
    batch_size: 256
    validation_split: 0.1